root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/loopze ./cmd/loopze"
  bin = "./tmp/loopze"
  full_bin = "./tmp/loopze --port 1880 --data-dir ./data --log-level debug"
  include_ext = ["go"]
  exclude_dir = ["bin", "build", "tmp", "frontend", "web/dist", "data"]
  delay = 500
  kill_delay = 500
  rerun = false

[log]
  time = false

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
