<script setup lang="ts">
import { useConfigSelector } from '@/composables/useConfigSelector'
import FormInput from '@/components/ui/FormInput.vue'
import FormSelect from '@/components/ui/FormSelect.vue'
import FormCheckbox from '@/components/ui/FormCheckbox.vue'
import FormField from '@/components/ui/FormField.vue'
import NumberInput from '@/components/ui/NumberInput.vue'
import SectionHeader from '@/components/ui/SectionHeader.vue'
import ToggleGroup from '@/components/ui/ToggleGroup.vue'
import UserPropertiesEditor from '@/components/ui/UserPropertiesEditor.vue'
import { useNodeProperty } from '@/composables/useNodeProperty'
import {
  QOS_LEVELS,
  PAYLOAD_FORMAT_OPTIONS,
  MQTT_IN_OUTPUT_FORMATS,
  MQTT_REQUEST_TIMEOUT_MODES,
} from './enums'

const { options: brokerOptions, openNewConfig, openEditConfig } = useConfigSelector('mqtt-broker')

const broker = useNodeProperty<string>('broker', '')
const topic = useNodeProperty<string>('topic', '')
const qos = useNodeProperty<number>('qos', 0)
const retain = useNodeProperty<boolean>('retain', false)
const responseTopicPrefix = useNodeProperty<string>('responseTopicPrefix', 'loopze/response')
const timeout = useNodeProperty<number>('timeout', 30)
const timeoutMode = useNodeProperty<string>('timeoutMode', 'error')
const responseFormat = useNodeProperty<string>('responseFormat', 'string')

const defaultUserProperties = useNodeProperty<Record<string, string>>('defaultUserProperties', {})
const defaultContentType = useNodeProperty<string>('defaultContentType', '')
const defaultMessageExpiry = useNodeProperty<number>('defaultMessageExpiry', 0)
const defaultPayloadFormat = useNodeProperty<number>('defaultPayloadFormat', 0)
</script>

<template>
  <div class="flex flex-col gap-3">
    <FormField label="Broker">
      <template #action>
        <button
          v-if="broker"
          class="text-[9px] uppercase tracking-wider text-terminal-text-dim hover:text-accent transition-colors"
          @click="openEditConfig(broker)"
        >Edit</button>
        <button
          class="text-[9px] uppercase tracking-wider text-terminal-text-dim hover:text-accent transition-colors"
          @click="openNewConfig()"
        >+ New</button>
      </template>
      <FormSelect
        v-model="broker"
        :options="brokerOptions"
        placeholder="Select broker..."
      />
    </FormField>

    <FormField label="Request topic" hint="Falls back to msg.topic when empty.">
      <FormInput
        v-model="topic"
        placeholder="rpc/devices/42/getState"
        mono
      />
    </FormField>

    <FormField label="QoS">
      <FormSelect v-model="qos" :options="QOS_LEVELS" />
    </FormField>

    <FormCheckbox v-model="retain" label="Retain request on broker" />

    <FormField label="Response topic prefix" hint="Full topic: <prefix>/<random-uuid>">
      <FormInput
        v-model="responseTopicPrefix"
        placeholder="loopze/response"
        mono
      />
    </FormField>

    <FormField label="Response format" hint="JSON falls back to String on parse failure (sets msg.parseError)">
      <FormSelect v-model="responseFormat" :options="MQTT_IN_OUTPUT_FORMATS" />
    </FormField>

    <FormField label="Timeout" hint="0 = no timeout (request stays inflight until response or stop)">
      <NumberInput v-model="timeout" :min="0" unit="sec" />
    </FormField>

    <FormField label="On timeout">
      <ToggleGroup v-model="timeoutMode" :options="MQTT_REQUEST_TIMEOUT_MODES" />
    </FormField>

    <SectionHeader title="MQTT v5 Default Properties">
      <div class="flex flex-col gap-2">
        <FormField label="Content Type">
          <FormInput v-model="defaultContentType" placeholder="e.g. application/json" mono />
        </FormField>
        <FormField label="Message Expiry">
          <NumberInput v-model="defaultMessageExpiry" :min="0" unit="sec" />
        </FormField>
        <FormField label="Payload Format">
          <FormSelect v-model="defaultPayloadFormat" :options="PAYLOAD_FORMAT_OPTIONS" />
        </FormField>
        <p class="text-[9px] text-terminal-text-dim leading-relaxed mt-1">
          msg fields override these defaults per request:
          <span class="font-mono text-accent">msg.contentType</span>,
          <span class="font-mono text-accent">msg.messageExpiry</span>,
          <span class="font-mono text-accent">msg.payloadFormat</span>,
          <span class="font-mono text-accent">msg.userProperties</span>.
          <span class="font-mono text-accent">msg.responseTopic</span> and
          <span class="font-mono text-accent">msg.correlationData</span> are
          generated by the node and ignored if set on input.
        </p>
      </div>
    </SectionHeader>

    <SectionHeader title="Default User Properties">
      <UserPropertiesEditor v-model="defaultUserProperties" />
    </SectionHeader>
  </div>
</template>
